services:
  sploosh-ai-hockey-analytics-app:
    build:
      # This is the path to your application source
      context: ../../../apps/sploosh-ai-hockey-analytics
      # This is the path to the Dockerfile relative to your application source
      dockerfile: ../../docker/sploosh-ai-hockey-analytics/development/app/Dockerfile
      args:
        GIT_HASH: ${GIT_HASH:-unknown}
        GIT_DATE: ${GIT_DATE:-unknown}
    ports:
      - "3000:3000"
    volumes:
      - ../../../apps/sploosh-ai-hockey-analytics:/app

      # Add /app/node_modules to the volume to prevent the node_modules directory from being overwritten by the first volume mount
      - /app/node_modules
    environment:
      - NODE_ENV=development
    labels:
      ai.sploosh.application: "Next.js"
      ai.sploosh.project: "sploosh-ai-hockey-analytics"
