name: Semantic PR Check

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: read

jobs:
  check-pr-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "Checking PR title: $PR_TITLE"
          
          # Check if title starts with valid type (including breaking change !)
          if [[ ! "$PR_TITLE" =~ ^(feat!|feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert): ]]; then
            echo "❌ PR title must start with one of: feat:, feat!:, fix:, docs:, style:, refactor:, perf:, test:, build:, ci:, chore:, revert:"
            echo "See CONTRIBUTING.md for more details on commit message format."
            exit 1
          fi
          
          echo "✅ PR title format is valid"

      - name: Check Breaking Change Format
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          
          # Check for breaking change indicator
          if [[ "$PR_TITLE" =~ ^feat!: ]]; then
            echo "⚠️ Breaking change detected in PR title"
            echo "This will trigger a major version bump"
          fi 