name: Semantic PR Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-format:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in either PR title or description should:
            - Start with a lowercase letter
          validateSingleCommit: false 