name: Version Bump

on: 
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Debug Info
        run: |
          echo "Current working directory:"
          pwd
          echo "Directory contents:"
          ls -la
          
      - name: Install dependencies
        run: npm install
          
      - name: Test Version Bump
        run: |
          # Test minor bump
          echo "Testing minor version bump..."
          
          # Bump root package.json
          npm version minor --no-git-tag-version
          
          # Get new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "New version will be: ${NEW_VERSION}"
          
          # Bump app package.json
          cd apps/sploosh-ai-hockey-analytics
          npm version $NEW_VERSION --no-git-tag-version
          
          # Show results (using grep with exact version line match)
          echo "Root package.json version:"
          grep '"version":' ../../package.json | head -n 1
          echo "App package.json version:"
          grep '"version":' package.json | head -n 1

permissions:
  contents: write
  pull-requests: write
